### ISSUE TITLE
[offtopic] contact

### ISSUE THREAD

**Issue by vladkorotnev** [samyuu/TotallyLegitArcadeController#1]
Hello, may i contact you for some discussion related to the project privately in some form? Email would be preferrable. same username as here at gmail dot com. Thanks!

**Comment by samyuu** [comment]
Hello, out of privacy reasons I do not wish to disclose my email. If it is not too much of an inconvenience to you, please feel free to contact me on discord under `samyuu#7582`.

**Comment by vladkorotnev** [comment]
Sure, I'll sign up for discord and contact later this evening (Tokyo standard time).
