### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by OiginYX** [samyuu/TotallyLegitArcadeController#12]
When i run the game, there is no sound.I try to use the update patch.txt ,but it is no use.

**Comment by BINiPad1999** [comment]
there's a patch exe on the server that fixed this problem.

**Comment by OiginYX** [comment]
thanks a lot.i tried to upgrade the sound card drive,and i succeed.

**Comment by Jakelshooter** [comment]
> there's a patch exe on the server that fixed this problem.

what server you mean exactly?
sorry im new to this
