### ISSUE TITLE
diva.exe crashes once tlac.exe opens.

### ISSUE THREAD

**Issue by BaaconHaawk** [samyuu/TotallyLegitArcadeController#2]
I have a NVIDIA GeForce GTX 965M graphics card, I have win10, I've prepatched and done everything correctly but tlac always causes diva.exe to crash. Same thing happened with PDA and elac once the elac4.0 update came out.

**Comment by Josevangaal** [comment]
Yeah, mine too. I have to open diva+elac/tlac at least 10 times for pda/pdaft to work.😖

**Comment by vladkorotnev** [comment]
Put it in a bat file, e.g. named game.bat, like so

```
cd /d %~dp0
start diva.exe -hdtv1080
timeout 10
tlac\tlac.exe
```

Then instead of diva.exe launch game.bat.
Works for me every single time.

**Comment by asps1726** [comment]
> I have a NVIDIA GeForce GTX 965M graphics card, I have win10, I've prepatched and done everything correctly but tlac always causes diva.exe to crash. Same thing happened with PDA and elac once the elac4.0 update came out.



> Yeah, mine too. I have to open diva+elac/tlac at least 10 times for pda/pdaft to work.

you all use notebook? is that your NVIDIA GPU work with diva.exe? the system use intel gpu in default

**Comment by vladkorotnev** [comment]
If you can run diva.exe without TLAC and just have it get stuck on any error, then GPU isn't the issue. It also might require a specific audio codec too btw, realtek ALC886 to be precise, but I haven't tested on anything other than that.

There seems to be something about tlac.exe in the way it sideloads the DLL which crashes diva.exe if you launch tlac *before* the black window with the text 「データ初期化 something something」 appears (before the engine is ready). Hence the timeout command in the bat file above.

Just give diva.exe some time to load before launching tlac.

**Comment by Josevangaal** [comment]
> If you can run diva.exe without TLAC and just have it get stuck on any error, then GPU isn't the issue. It also might require a specific audio codec too btw, realtek ALC886 to be precise, but I haven't tested on anything other than that.
> 
> There seems to be something about tlac.exe in the way it sideloads the DLL which crashes diva.exe if you launch tlac _before_ the black window with the text 「データ初期化 something something」 appears (before the engine is ready). Hence the timeout command in the bat file above.
> 
> Just give diva.exe some time to load before launching tlac.

I already made the bat file,and I also waited and lunched tlac after the text 「データ初期化 something something」. It still crashes:(

**Comment by BaaconHaawk** [comment]
> If you can run diva.exe without TLAC and just have it get stuck on any error, then GPU isn't the issue. It also might require a specific audio codec too btw, realtek ALC886 to be precise, but I haven't tested on anything other than that.
> 
> There seems to be something about tlac.exe in the way it sideloads the DLL which crashes diva.exe if you launch tlac _before_ the black window with the text 「データ初期化 something something」 appears (before the engine is ready). Hence the timeout command in the bat file above.
> 
> Just give diva.exe some time to load before launching tlac.

I can use a .bat and use a timeout interval all the way from 0-20 and it'll never work, i can even manually launch tlac before the text or when it's loading and checking to connect to diva.net, it's just tlac, since i can perfectly load up diva by itself.

**Comment by samyuu** [comment]
Since you have mentioned ELAC v4 I suspect this to be caused by the PlayerDataManager component and an issue with its config file possibly due to it not being encoded correctly.
To confirm this please disable all components inside `components.ini` and toggling them back on one by one each before restarting the game.
If this is not the case, are there by any chance unicode characters in either the diva or the TLAC path?

**Comment by BaaconHaawk** [comment]
> Since you have mentioned ELAC v4 I suspect this to be caused by the PlayerDataManager component and an issue with its config file possibly due to it not being encoded correctly.
> To confirm this please disable all components inside `components.ini` and toggling them back on one by one each before restarting the game.
> If this is not the case, are there by any chance unicode characters in either the diva or the TLAC path?

It turned out to be the playerdata.ini, I grabbed a fresh one from the TLAC.7z and it worked like a charm, but I assumed it wasn't since I encoded it with UTF-8 and there were no weird characters. (I just tested it out and it's my laptop or something, i encoded a fresh playerdata.ini, in which i did not edit it all, and it crashed. So it's something my laptop has with encoding problems)

**Comment by BaaconHaawk** [comment]
> Since you have mentioned ELAC v4 I suspect this to be caused by the PlayerDataManager component and an issue with its config file possibly due to it not being encoded correctly.
> To confirm this please disable all components inside `components.ini` and toggling them back on one by one each before restarting the game.
> If this is not the case, are there by any chance unicode characters in either the diva or the TLAC path?

It turned out to be the playerdata.ini, I grabbed a fresh one from the TLAC.7z and it worked like a charm, but I assumed it wasn't since I encoded it with UTF-8 and there were no weird characters. (I just tested it out and it's my laptop or something, i encoded a fresh playerdata.ini, in which i did not edit it all, and it crashed. So it's something my laptop has with encoding problems)
