### ISSUE TITLE
diva.exe does nothing upon launch

### ISSUE THREAD

**Issue by Zazazasu** [samyuu/TotallyLegitArcadeController#25]
I followed the instructions but after patching and running diva.exe and tlac.exe, no game window opens. The command prompt window just stays empty and opened. I tried the same process with elac instead and for some reason it works.

**Comment by cainan-c** [comment]
ELAC is for Project DIVA Arcade, while TLAC is for Project DIVA Arcade Future Tone.
If your diva.exe worked with ELAC but not TLAC, you're running DIVA Arcade and not DIVA Arcade Future Tone. To use TLAC, find a dump of Arcade Future Tone

**Comment by Zazazasu** [comment]
Well damn how could I miss that. Does it say that anywhere on tlac's page that I didn't see?
