### ISSUE TITLE
My commands not work

### ISSUE THREAD

**Issue by tainannn** [samyuu/TotallyLegitArcadeController#7]
my commands do not work, I open the game and it stays on the black screen with the blue button but can not do anything.

**Comment by samyuu** [comment]
I do not believe this issue to be related to this program so I'm closing this for now.
You have not provided sufficient information for me to make anything other than a guess so please confirm you have followed the [Usage](https://github.com/samyuu/TotallyLegitArcadeController#usage) guide and your hardware meets the minimum requirements to run the game.
